version: '3.8'

services:
  database:
    image: clickhouse/clickhouse-server:latest
    container_name: database
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ../products/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ../products/Data.csv:/data/Data.csv

  backend:
    build:
      context: ../app
      dockerfile: Dockerfile
    container_name: backend
    volumes:
      - /app:/app
    env_file:
      - ../.env
    ports:
      - "8000:8000"
    depends_on:
      - database